name = "CheegerConvexificationBounds"
uuid = "839d17a8-5eef-4f7a-ba95-c40dd0380129"
authors = ["Melanie Siebenhofer <melaniesi@edu.aau.at> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"
